@file:Suppress("ObjectPropertyName", "unused")

package wing.tree.multiplication.table.extension.property

import wing.tree.multiplication.table.model.Percentage

val Percentage.Companion.`1`: Percentage get() = Percentage(0.01F)
val Percentage.Companion.`100`: Percentage get() = Percentage(1.00F)
val Percentage.Companion.`11`: Percentage get() = Percentage(0.11F)
val Percentage.Companion.`16`: Percentage get() = Percentage(0.16F)
val Percentage.Companion.`2`: Percentage get() = Percentage(0.02F)
val Percentage.Companion.`3`: Percentage get() = Percentage(0.03F)
val Percentage.Companion.`32`: Percentage get() = Percentage(0.32F)
val Percentage.Companion.`36`: Percentage get() = Percentage(0.36F)
val Percentage.Companion.`38`: Percentage get() = Percentage(0.38F)
val Percentage.Companion.`4`: Percentage get() = Percentage(0.04F)
val Percentage.Companion.`40`: Percentage get() = Percentage(0.40F)
val Percentage.Companion.`42`: Percentage get() = Percentage(0.40F)
val Percentage.Companion.`48`: Percentage get() = Percentage(0.48F)
val Percentage.Companion.`5`: Percentage get() = Percentage(0.05F)
val Percentage.Companion.`6`: Percentage get() = Percentage(0.06F)
val Percentage.Companion.`60`: Percentage get() = Percentage(0.60F)
val Percentage.Companion.`8`: Percentage get() = Percentage(0.08F)
val Percentage.Companion.`89`: Percentage get() = Percentage(0.89F)
val Percentage.Companion.`92`: Percentage get() = Percentage(0.92F)
val Percentage.Companion.`94`: Percentage get() = Percentage(0.94F)
val Percentage.Companion.`96`: Percentage get() = Percentage(0.96F)
val Percentage.Companion.`97`: Percentage get() = Percentage(0.97F)
val Percentage.Companion.fullyOpaque: Percentage get() = Percentage(1.00F)
val Percentage.Companion.half: Percentage get() = Percentage(Float.half)
